package com.lam.quan.intuitrepo.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 * Github repo response model from repos API
 */
@Parcelize
data class Repo(val id:String = "",
                val node_id:String = "",
                val name:String   = "",
                val full_name:String="",
                val private:Boolean=false,
                val owner:User = User(),
                val html_url:String = "",
                val description:String = "",
                val fork:Boolean = false,
                val url:String = "",
                val forks_url:String = "",
                val keys_url:String = "",
                val collaborators_url:String = "",
                val teams_url:String = "",
                val hooks_url:String = "",
                val issue_events_url:String = "",
                val events_url : String = "",
                val assignees_url: String = "",
                val branches_url:String = "",
                val tags_url:String = "",
                val blobs_url:String = "",
                val git_tags_url:String = "",
                val git_refs_url:String = "",
                val trees_url:String = "",
                val statuses_url:String = "",
                val languages_url:String = "",
                val stargazers_url:String = "",
                val contributors_url:String = "",
                val subscribers_url:String = "",
                val subscription_url:String = "",
                val commits_url:String = "",
                val git_commits_url:String = "",
                val comments_url:String = "",
                val issue_comment_url:String = "",
                val contents_url:String = "",
                val compare_url:String = "",
                val merges_url:String = "",
                val archive_url:String = "",
                val downloads_url:String = "",
                val issues_url:String = "",
                val pulls_url:String = "",
                val milestones_url: String = "",
                val notifications_url:String ="",
                val labels_url:String = "",
                val releases_url:String = "",
                val deployments_url:String = "",
                val created_at:String = "",
                val updated_at:String = "",
                val pushed_at:String = "",
                val git_url:String = "",
                val ssh_url:String = "",
                val clone_url:String = "",
                val svn_url:String = "",
                val homepage:String? = null,
                val size:Int = 0,
                val stargazers_count: Int = 0,
                val watchers_count:Int = 0,
                val language:String = "",
                val has_issues: Boolean = false,
                val has_projects: Boolean = false,
                val has_downloads: Boolean = false,
                val has_wiki: Boolean = true,
                val has_pages:Boolean = false,
                val forks_count:Int = 0,
                val mirror_url:String? = null,
                val archived:Boolean = false,
                val disabled:Boolean = false,
                val open_issues_count:Int = 1,
                val forks:Int = 0,
                val open_issues:Int = 1,
                val watchers:Int = 0,
                val default_branch:String = "master"
                ): Parcelable